
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import morgan from 'morgan';
import cookieParser from 'cookie-parser';
import mongoSanitize from 'express-mongo-sanitize';
import rateLimit from 'express-rate-limit';
import swaggerUi from 'swagger-ui-express';


import { errorHandler } from './middleware/errorHandler.js';
import { AppError } from './utils/appError.js';
import { ERROR_CODES } from './constants/errorCodes.js';

import authRoutes from './routes/auth.routes.js'
import userRoutes from './routes/user.routes.js'
import  recordRoutes from './routes/record.routes.js'
import  dashboardRoutes from './routes/dashboard.routes.js'

import { swaggerSpec } from './config/swagger.js';

const app = express();


// Set security-related HTTP headers
app.use(helmet());

// CORS
const allowedOrigins = (process.env.ALLOWED_ORIGINS || 'http://localhost:5000').split(',');
app.use(
  cors({
    origin: (origin, callback) => {
      // Allow requests for Postman in dev
      if (!origin || allowedOrigins.includes(origin)) {
        callback(null, true);
      } else {
        callback(new Error('Not allowed by CORS'));
      }
    },
    credentials: true, // Allow cookies
    methods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization'],
  })
);

app.use(mongoSanitize());

// Rate Limiting
const globalLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, 
  max: 100,                  // max 100 requests per IP per window
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    success: false,
    message: 'Too many requests from this IP. Please try again after 15 minutes.',
    errorCode: 'RATE_LIMIT_EXCEEDED',
  },
});

const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 20,
  message: {
    success: false,
    message: 'Too many authentication attempts. Please try again after 15 minutes.',
    errorCode: 'RATE_LIMIT_EXCEEDED',
  },
});

app.use('/api', globalLimiter);
app.use('/api/auth', authLimiter);


app.use(express.json({ limit: '10kb' }));       
app.use(express.urlencoded({ extended: true })); 
app.use(cookieParser());                      

// HTTP request logging (skip in test environment)
if (process.env.NODE_ENV !== 'test') {
  app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
}


app.get('/health', (req, res) => {
  res.status(200).json({
    success: true,
    message: 'FinanceControl API is running.',
    environment: process.env.NODE_ENV,
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  });
});

app.get('/',(req,res)=>{
    res.status(200).json({
        statusCode:200,
        success:true,
        message:"This is the backend of Financial Control Server"
    })
})

// API Docs (Swagger UI)- Generated by AI 
 
const swaggerUiOptions = {
  customCss: `
    .swagger-ui .topbar { background: #0d0f12; border-bottom: 1px solid #1e2230; }
    .swagger-ui .topbar-wrapper img { content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 40'%3E%3Ctext y='28' font-family='monospace' font-size='18' fill='%234ade80'%3E◈ Finance-Control %3C/text%3E%3C/svg%3E"); width: 160px; }
    .swagger-ui .info .title { color: #e2e8f0; font-family: monospace; }
    .swagger-ui .info .description p { color: #94a3b8; }
    body .swagger-ui { background: #0d0f12; }
    .swagger-ui .scheme-container { background: #141720; border: 1px solid #1e2230; padding: 12px 20px; }
    .swagger-ui .opblock-tag { border-bottom: 1px solid #1e2230; color: #e2e8f0; font-family: monospace; }
    .swagger-ui .opblock.opblock-post   .opblock-summary { background: rgba(73,204,144,.07); }
    .swagger-ui .opblock.opblock-get    .opblock-summary { background: rgba(97,175,254,.07); }
    .swagger-ui .opblock.opblock-patch  .opblock-summary { background: rgba(252,161,48,.07);  }
    .swagger-ui .opblock.opblock-delete .opblock-summary { background: rgba(249,62,62,.07);   }
    .swagger-ui .btn.authorize { background: #052e1c; border-color: #4ade80; color: #4ade80; font-family: monospace; }
    .swagger-ui .btn.authorize svg { fill: #4ade80; }
  `,
  customSiteTitle: 'api documentation',
  swaggerOptions: {
    persistAuthorization: true,     // Keep token across page refreshes
    tryItOutEnabled: true,          // Open "Try it out" by default
    displayRequestDuration: true,   // Show response time
    docExpansion: 'list',           // Collapse by default, show tag list
    filter: true,                   // Enable search box
    syntaxHighlight: { theme: 'agate' },
  },
};
 
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, swaggerUiOptions));
 
// Expose raw OpenAPI JSON for tooling (Postman import, code gen, etc.)
app.get('/api-docs.json', (req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.send(swaggerSpec);
});



// API Routes 
app.use('/api/auth', authRoutes);
app.use('/api/records', recordRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/users',     userRoutes);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

app.use((req, res, next) => {
  next(new AppError(`Route ${req.method} ${req.originalUrl} not found.`, 404, ERROR_CODES.NOT_FOUND));
});

app.use(errorHandler);

export default app;